=== mohrndorf/repairvision/plugins.silift/org.sidiff.common/dtd/org.sidiff.common.io.map.dtd
<!ELEMENT Map (MapEntry*)>
<!ATTLIST Map type CDATA #IMPLIED >

<!ELEMENT MapEntry EMPTY>
<!ATTLIST MapEntry
	key CDATA #REQUIRED 
	value CDATA #REQUIRED >

=== mohrndorf/repairvision/plugins.silift/org.sidiff.common/config/org.sidiff.common.xml.EntityResolver.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Map SYSTEM "http://pi.informatik.uni-siegen.de/SiDiff/org.sidiff.common.io.map.dtd">
<Map type="DTDMappings">
	<MapEntry
			key="http://pi.informatik.uni-siegen.de/SiDiff/core.annotations.dtd"
			value="core.annotations.dtd"/>		
	<MapEntry
			key="http://pi.informatik.uni-siegen.de/SiDiff/core.candidates.constraints.dtd"
			value="core.candidates.constraints.dtd"/>
	<MapEntry
			key="http://pi.informatik.uni-siegen.de/SiDiff/core.compare.sidiffcompare.dtd"
			value="core.compare.sidiffcompare.dtd"/>
	<MapEntry
			key="http://pi.informatik.uni-siegen.de/SiDiff/core.datamodel.graph.dtd"
			value="core.datamodel.graph.dtd"/>	
	<MapEntry
			key="http://pi.informatik.uni-siegen.de/SiDiff/core.difference.asymetric.dtd"
			value="core.difference.asymetric.dtd"/>	
	<MapEntry
			key="http://pi.informatik.uni-siegen.de/SiDiff/core.global.configuration.dtd"
			value="core.global.configuration.dtd"/>
	<MapEntry
			key="http://pi.informatik.uni-siegen.de/SiDiff/core.matching.correspondings.dtd"
			value="core.matching.correspondings.dtd"/>	
	<MapEntry
			key="http://pi.informatik.uni-siegen.de/SiDiff/core.matching.iterative.dtd"
			value="core.matching.iterative.dtd"/>	
	<MapEntry
			key="http://pi.informatik.uni-siegen.de/SiDiff/core.io.map.dtd"
			value="org.sidiff.common.io.map.dtd"/>	
	<!-- New Core Bundels! -->		
	<MapEntry
			key="http://pi.informatik.uni-siegen.de/SiDiff/org.sidiff.core.compare.calculator.default.dtd"
			value="org.sidiff.core.compare.calculator.default.dtd"/>	
</Map>
